# Generated by Django 6.1 on 2026-08-25 14:51

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Registered / physical address'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Primary contact person', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=customers.models.tenant_logo_path),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(blank=True, default='#000000', help_text='Hex color, e.g. #1A73E8', max_length=7),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Hex color, e.g. #F5F5F5', max_length=7),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tenant_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tpin',
            field=models.CharField(blank=True, max_length=20, verbose_name='TPIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Company / organisation name', max_length=150),
        ),
    ]
