# Generated by Django 6.1 on 2026-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sms_base_url', models.CharField(blank=True, max_length=255)),
                ('sms_source', models.CharField(blank=True, max_length=50)),
                ('sms_senderid', models.CharField(blank=True, max_length=50)),
                ('sms_username', models.CharField(blank=True, max_length=50)),
                ('sms_password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_email',
            field=models.EmailField(blank=True, help_text="Primary contact person's email", max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_phone',
            field=models.CharField(blank=True, help_text="Primary contact person's phone number", max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_position',
            field=models.CharField(blank=True, help_text="Primary contact person's job title/role", max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
